name: "project"
services:
  backend:
    build:
      context: .
      dockerfile: ./tomcat.dockerfile
      args:
        - WAR_FILE=labboot-back/target/labboot-back.war
  frontend:
    build:
      context: .
      dockerfile: ./nginx.dockerfile
      args:
        - PUBLISH_DIR=labvue-front/dist
proxy:
    build:
      context: ./resverse-proxy/
      dockerfile: ./caddy.dockerfile
    ports:
      - "9000:80"
